---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kute.
--- DateTime: 2019/12/22 11:13
---

local json_util = {}
local json = require("cjson")

function json_util.encode(val)
    res = nil
    pcall(function(str)
        res = json.encode(str)
    end, val)
    return res
end

function json_util.decode(val)
    res = nil
    pcall(function(str)
        res = json.decode(str)
    end, val)
    return res
end

return json_util