---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kute.
--- DateTime: 2019/11/21 11:37
---
local config = require("lapis.config")

-- 配置开发测试环境
config({"dev", "test"}, {
    port = 8080,
    num_workers = 4,
    code_cache = "on",
    worker_connection = 65535,
    measure_performance = true
})

-- 配置生产环境
config("prod", {
    port = 8080,
    num_workers = 4,
    code_cache = "on",
    worker_connection = 65535,
    measure_performance = false
})